### PR TITLE
Add timestamps to history results

### LINKED ISSUE #82: History results have no timestamps
I tapped = on Nov 8, 2022 @ 10:00:21. Then later I made another calculation and yaooed = on Nov 9, 2022 @ 08:04:01. Both are recorded history, but no idea when I made them (tapped =).

### PR DESCRIPTION
**Pull request by lefterisgar**
Fixes #82. I'm not sure if you are okay with the paddings, spacing, etc...
Here is a quick screenshot:
Screenshot_20230213-005107_crDroid Home

### CODE REVIEW

**Comment by Darkempire78** [comment]
I found an issue, if you upgrade the app with this version, the app will crash because the former history does not have the time element

```Kotlin
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.darkempire78.opencalculator, PID: 8075
    java.lang.NumberFormatException: null
        at java.lang.Long.parseLong(Long.java:699)
        at java.lang.Long.parseLong(Long.java:861)
        at com.darkempire78.opencalculator.HistoryAdapter$HistoryViewHolder.bind(HistoryAdapter.kt:62)
        at com.darkempire78.opencalculator.HistoryAdapter.onBindViewHolder(HistoryAdapter.kt:29)
        at com.darkempire78.opencalculator.HistoryAdapter.onBindViewHolder(HistoryAdapter.kt:14)

```

**Comment by Darkempire78** [comment]
It may be beter to display "Today", "Yesterday" or "December 1, 2022" instead of 

> 

I fixed it ([09cab89](https://github.com/Darkempire78/OpenCalc/pull/159/commits/09cab89165b18af4b8f1ed95cb9b500706d96e84)), it remove the time text if it does not exists

**Comment by Darkempire78** [comment]
It may be beter to display "Today", "Yesterday" or "December 1, 2022"
We can group all the calculations of one day. Now each calculation has its own date even if I made them with 2 seconds difference

**Comment by lefterisgar** [comment]
> It may be beter to display "Today", "Yesterday" or "December 1, 2022" We can group all the calculations of one day. Now each calculation has its own date even if I made them with 2 seconds difference

Yes, that is a valid issue.

**Comment by Darkempire78** [comment]
> 

It's not a problem, push your update, I will group them

**Comment by Darkempire78** [comment]
@lefterisgar I grouped the results by date, what do you think about the UI ? 😀

**Comment by lefterisgar** [comment]
> @lefterisgar I grouped the elements by date, what do you think about the UI ? grinning

I think it looks reeeally cool! Thanks for the improvements!

**Pull request merged**
