### PR TITLE
[Refactor] Reduce the code by removing duplication of Calculator Pad Text

### PR DESCRIPTION
**Pull request by Hafiz-Waleed-Hussain**
Improve the Calculator input pad.

### CODE REVIEW

**Comment by Darkempire78** [comment]
The keyPadMappingToDisplay function won't work for buttons like "cos" or "-", because cos adds " cos(" when clicked and not just "cos", for "-", it's not the same character that is  displayed on the button

**Comment by Darkempire78** [comment]
I think it should be used only for numbers

**Comment by Hafiz-Waleed-Hussain** [comment]
Nice catch; I think we should have unit tests for these cases. So we can catch up during the development phase.

**Comment by Darkempire78** [comment]
> Nice catch; I think we should have unit tests for these cases. So we can catch up during the development phase.

Yes, you are right it can be very useful

**Comment by Darkempire78** [comment]
@Hafiz-Waleed-Hussain Do you want to work on this pull request or should I close it?

**Comment by Hafiz-Waleed-Hussain** [comment]
Ops, I forgot. I will create a new pull request later.

**Pull request closed without merging**
