### PR TITLE
fix: Comma seperator not working inside parenthesis

### LINKED ISSUE #403: Comma seperator not working inside parenthesis
**Describe the bug**
Comma at every thousandth place not coming inside parenthesis but only 1 comma no matter how many zeros. This happens when you add a lot of parenthesis.

**To Reproduce**
1. Do some calculation with parenthesis and inside as well.
2. After certain number of parenthesis comma seperator will malfunction.

**Expected behavior**
Comma seperator should work properly.

**Screenshots/videos**
Screenshot_20240112_202404_Calculator

**Smartphone:**
 - Device: Samsung Galaxy S21 FE
 - OS: Android 14
 - App version: v2.3.1 (apk from GitHub)
 - Language: English

**Additional context**
It might be related to locality as in Indian number system, 1st comma seperator comes at 1000th place and then at every 100th place.

### PR DESCRIPTION
**Pull request by muryno**
Fixes #403 

fix: In the original code, there were a few hiccups in handling number formatting, especially around the use of decimal and grouping separators. To address this, I revised the logic to accurately incorporate these separators into numbers. I also made sure that when numbers are being formatted and replaced back into the text, we only replace the first instance of each number to avoid duplicating changes. These tweaks ensure that numbers within any text are formatted correctly, maintaining the intended structure and readability.

### CODE REVIEW

**Comment by muryno** [comment]
Fix for https://github.com/Darkempire78/OpenCalc/issues/403

**Comment by Darkempire78** [comment]
I will check that as soon as possible

**Comment by muryno** [comment]
Fixes: #416

**Comment by muryno** [comment]
Fixes #403

**Comment by muryno** [comment]
> I will check that as soon as possible

@Darkempire78 are you able to review my MR 😊

**Comment by Darkempire78** [comment]
Sorry @muryno for the wait... I was very busy
Btw, there is a conflict, can you fix it please ?

**Comment by Darkempire78** [comment]
In fact, it was already fixed thanks to https://github.com/Darkempire78/OpenCalc/pull/433

**Pull request closed without merging**
