### PR TITLE
Change text color on error & Other improvements

### PR DESCRIPTION
**Pull request by lefterisgar**
I think that adding some color can greatly improve the overall UX of the app. This PR changes the text color to red if an error occurs and then resets it if a change is detected. Also adds another improvements, like removing deprecated methods and cleanup.

### CODE REVIEW

**Comment by lefterisgar** [comment]
Update: Breaks light theme

**Comment by Darkempire78** [comment]
Works well! But the color is terrible x)

**Comment by Darkempire78** [comment]
I do not know if this color is perfect, but it looks better I think (it would be nice to have a design expert look at the project one day lmao)

**Comment by Darkempire78** [comment]
> Update: Breaks light theme
> 
> DO NOT MERGE, I have fixed it and will push it today.

Sure, I saw the bug, ping me when it is good

**Comment by lefterisgar** [comment]
I messed a few things up while rebasing. Could you please cherry-pick or send me the hash of the commit where you changed the color?

**Comment by Darkempire78** [comment]
> 



> I messed a few things up while rebasing. Could you please cherry-pick or send me the hash of the commit where you changed the color?

768e270a45361475bb40be1a2e31eba6c159bfed

**Comment by lefterisgar** [comment]
I think we are ready to merge.

**Comment by lefterisgar** [comment]
Update: Managed to get apk size from 4.5MB to just under 2MB.

**Comment by Darkempire78** [comment]
> 



> Update: Managed to get apk size from 4.5MB to just under 2MB.

Thank for that, 
for the next time open another pull request if it is not related to the aim of the current pull request please :)

**Pull request merged**
