### PR TITLE
#314  fix: issue with factorial decimal number

### LINKED ISSUE #314: Factorials on floating point values
**Describe the bug**

"Factorial operation" on "floating point values" is returning "bad values."

(Examples)
.9! = 0.1416504592
0.9! = 0.7016202463
9.9! = 0.7016202463
π! = 5.1427625509
3.1415! = 0.2075431593

**To Reproduce**
1. Go to 'calculator.' I was in portrait orientation
2. Click on '3' > '!'
3. Move cursor between '3' & '!' > click on '.' > '0'
4. Returned values are '6' > '  ' > '1'

**Expected behavior**

I expect '3!' to be equal to '3.0!' = '6'
It seems to ignore the 'whole part' of a non-integer number and does something very different when the 'whole part' is missing.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A51
 - OS: Android
 - Version 13
 - Language English

**Additional context**

"An approximation" for "positive non integer numbers"
https://en.wikipedia.org/wiki/Lanczos_approximation

### PR DESCRIPTION
**Pull request by muryno**
Fixes #314 

The issue arose because the original code overlooked decimal points when identifying numbers leading up to a factorial symbol, mishandling cases like "3.0!". By adding a check for decimals, the updated code now properly handles these numbers

Before 
old1
old2

MR result

Screenshot 2024-02-19 at 21 37 33

### CODE REVIEW

**Comment by inson1** [comment]
its wrong, '.' doesnt have to be always '.', it matters on your system languague

**Comment by muryno** [comment]
> DecimalFormatSymbols
@inson1  I saw that but if you try to debug the cause for why 50.0 ! != 50!

it is because the . is ignored and this function `private fun formatFactorial(calculation: String): String {`  always return case like 
**factorial(50(factorial(.0)) instead of factorial(50.0)**

adding the check in this PR fix the issue..



> @muryno its wrong, '.' doesnt have to be always '.', it matters on your languague
> 
> this is used for it "DecimalFormatSymbols.getInstance().decimalSeparator.toString()" and in main activity there is decimalSeparatorSymbol variable

**Comment by Darkempire78** [comment]
But factorial forms as "3.03!" still does not work

**Comment by muryno** [comment]
> But factorial forms as "3.03!" still does not work

I will take a look at this and update the code

**Comment by muryno** [comment]
@Darkempire78  The issue was due to precision loss from converting BigDecimal to double for mathematical operations, which can introduce inaccuracies in calculations, especially for functions like the Lanczos approximation that are sensitive to precision. 

I have updated the logic to minimizes precision loss by managing conversions between BigDecimal and double

**Comment by Darkempire78** [comment]
Thank you!

**Comment by Darkempire78** [comment]
@muryno I wasn't paying attention, but the pull request has created a problem. It no longer passes the calculation tests.
In fact `(3!)!` no longer works. 
image

**Comment by muryno** [comment]
> @muryno I wasn't paying attention, but the pull request has created a problem. It no longer passes the calculation tests. In fact `(3!)!` no longer works. image

@Darkempire78  will take a look at this today ..... or we can create a bug ticket and assign to me

**Comment by muryno** [comment]
@Darkempire78  MR fix https://github.com/Darkempire78/OpenCalc/pull/440

**Pull request merged**
