### PR TITLE
Remove deprecated kotlin-android-extensions & update/clean code

### PR DESCRIPTION
**Pull request by bonswouar**
- Removed `kotlin-android-extensions` and changed the Activities code accordingly (https://developer.android.com/topic/libraries/view-binding/migration)
- Upgraded dependencies, replaced deprecated `jcenter()` with `mavenCentral()`, disabled `Jetifier`
- Cleaned the code (mostly using `ktlint`)

I still have that warning left that I couldn't find how to fix, it seems `getPackageInfo` is the right way to do?!
image

_This PR should be safe as most of those changes are recommended by Android Studio or the official documentation, and everything seems to work properly;
although don't forget that I've started to learn Kotlin yesterday :smile:_

### CODE REVIEW

**Comment by bonswouar** [comment]
Oh and I wanted to try to implement a draggable panel (for the calculation history), using [SlidingPaneLayout](https://developer.android.com/reference/androidx/slidingpanelayout/widget/SlidingPaneLayout), but I couldn't figure out how it works yet

**Comment by Darkempire78** [comment]
> Oh and I wanted to try to implement a draggable panel (for the calculation history), using [SlidingPaneLayout](https://developer.android.com/reference/androidx/slidingpanelayout/widget/SlidingPaneLayout), but I couldn't figure out how it works yet

It seems that slidingpanelayout is only available for horizontal sliding

**Comment by Darkempire78** [comment]
Thanks! I will try to implement the sliding today

**Comment by Darkempire78** [comment]
For a strange reason nothing seems to work on the About page since this improvement xD

**Comment by bonswouar** [comment]
@Darkempire78 OH right Totally my bad, found the culprit, sorry!! https://github.com/Darkempire78/OpenCalc/pull/43

**Pull request merged**
