### PR TITLE
Multiple improvements

### PR DESCRIPTION
**Pull request by lefterisgar**
Hello and congratulations for releasing v2 of this awesome app! I've made a few improvements to it. Let me know if you want me to change something.

### Here is a list of what this PR fixes:

- sinus/cosinus (French) -> sine/cosine (English)
- Remove an unused string and reorganize existing ones
- Updated greek translation
- Only store the result to history if it's a number (and not NaN or +/- Infinity), just like other calculator apps do
- Display an error when dividing by 0 (the previous approach was to output +/- Infinity, which is only correct if we are talking about limits)
- Display an error on ln0 for the same reason as above
- Minor code refactoring and simplification

### CODE REVIEW

**Comment by Darkempire78** [comment]
It's not still perfect, sometimes there are some crashes

**Comment by lefterisgar** [comment]
Thanks for taking the time to perfect this PR! Are there still crashes after your last commit?

**Comment by Darkempire78** [comment]
> Thanks for taking the time to perfect this PR! Are there still crashes after your last commit?

I just forgot `withContext(Dispatchers.Main) {}`

**Comment by lefterisgar** [comment]
Maybe "syntax error" is more explanatory than "format error"?

**Comment by Darkempire78** [comment]
> Maybe "syntax error" is more explanatory than "format error"?

You are right, I change that

**Comment by Darkempire78** [comment]
Could you update the greek translation please ? After that I will merge it

**Comment by lefterisgar** [comment]
> Could you update the greek translation please ? After that I will merge it

Yes, of course!

**Comment by lefterisgar** [comment]
I see this line: `if (x.isNaN()) format_error = true` is used multiple times. Can this only be on top and apply to all cases?

**Comment by Darkempire78** [comment]
> I see this line: `if (x.isNaN()) format_error = true` is used multiple times. Can this only be on top and apply to all cases?

Yes I fixed that

**Comment by Darkempire78** [comment]
Thank you so much for your pull request :)

**Comment by lefterisgar** [comment]
Thanks for the awesome project! :)

**Pull request merged**
