### PR TITLE
Material Styles and Vector icon buttons

### PR DESCRIPTION
**Pull request by ac87**
As discussed in #124 

Updates to use Material3 base themes and switches symbol button icons for vectors to ensure they are consistently aligned in the middle of the buttons.

### CODE REVIEW

**Comment by Darkempire78** [comment]
Thank yiu so much! I'm extremely busy until Tuesday night, so I'll definitely be merging Tuesday night

**Comment by Darkempire78** [comment]
First of all, thank you for your help! Most of your PR is awesome. 
Here are some changes that should be reviewed:
- the condensed font is quite ugly especially for the "scientific" buttons (when unfolded)
- the scientific buttons don't have the ripple effect anymore
- the invisible buttons emptyScientistMode1 and emptyScientistMode2 on the contrary have a ripple effect when they should not have one
- I find the new images for the operators too bold, what do you think? More generally I think that all buttons are slightly too bold
- if not, I find the background a bit light when you are on the material you dark theme, it's certainly because you changed the color of the buttons

Otherwise it's great, thanks for your help!!

**Comment by Darkempire78** [comment]
where do you find all the operators in vector?

**Comment by ac87** [comment]
@Darkempire78 You are correct, 

- I've pulled the condensed font over where its wasn't actually used.

In your layout you've got many instances of `android:fontFamily="@style/RobotoFontCondensedLight"`
I assumed this meant the font was condensed however because the declaration is wrong its not actually in effect. The landscape buttons are still using condensed in this branch, I assume you don't want this?

- Fixed the flat buttons not rippling. Material3 is a pain to remove the background but not remove the ripple

- I have added scaling to the operator icons to make them smaller and nearer to your original text size operators

Happy to change things back (I think you can change this PR branch too)

As for the icons I made them in Inkscape then cleaned them up with https://www.svgminify.com/. They are pretty straightforward.

**Comment by Darkempire78** [comment]
@ac87 It seems good!
I just notice an issue in the amoled theme with the function buttons : 
image

Perhaps I should change the font for a better render. For example parenthesis are a little bit weird. I thing that a finer font would allow for a larger font size

**Comment by ac87** [comment]
Fixed the amoled theme by setting the material theme background color to the amoled pure black background color. 

https://material.io/blog/android-material-theme-color shows the different color that you can override in themes instead of adding new ones.

**Comment by Darkempire78** [comment]
Thanks!

**Comment by Darkempire78** [comment]
@ac87 I just realized that the theme "follow the system" does not support material you

**Comment by ac87** [comment]
@Darkempire78 So if the users device supports Material You the System option was to use that? I'm confused as the Material You selection follows the system dark/light too.

**Comment by Darkempire78** [comment]
> 

Yes that's it, Material You should override the dark/light theme if it is enebaled on the device

**Comment by ac87** [comment]
Just looking at the code before the PR

On Android 13, 

System = Material You (Following System Dark/Light)
Light = Default Theme (forced to light)
Dark = Default Theme (forced to dark)
Amoled
Material You = same as System. _Material You (Following System Dark/Light)_

I can easily restore System to show Material You when supported

but does it make more sense for it you then be

- System (Material You)
- Light
- Dark
- Amoled

as otherwise the first and last options are the same?

**Comment by Darkempire78** [comment]
> as otherwise the first and last options are the same?
That's true 🤔

**Comment by ac87** [comment]
Have a look at this, see if that makes sense, 
https://github.com/Darkempire78/OpenCalc/compare/main...ac87:OpenCalc:material-you-system

Removes the standalone Material You selection but shows "System (Material You)" for clarity. Would be valid to just say "System" still

**Pull request merged**
