### PR TITLE
Minor refactor

### PR DESCRIPTION
**Pull request by lefterisgar**
- Changed variable name (error_status -> errorStatus)
- Only calculate factorial if it's needed (it's not negative or infinity)

Also, I'm sorry for committing unrelated stuff to the previous PR. It's just that I feel I have overloaded you with PRs every now and then... :)

### CODE REVIEW

**Comment by Darkempire78** [comment]
If I remember, replace isNullOrEmpty() by isEmpty() did not works when I tried

**Comment by lefterisgar** [comment]
Okay, so I need to reset the PR to the previous commit?

**Comment by Darkempire78** [comment]
> Okay, so I need to reset the PR to the previous commit?

Yes please 😀

**Comment by lefterisgar** [comment]
> > Okay, so I need to reset the PR to the previous commit?
> 
> Yes please grinning

Done! 😀

**Comment by Darkempire78** [comment]
Thank you!

**Pull request merged**
