### PR TITLE
changes

### PR DESCRIPTION
**Pull request by sosauce2**
- changed gradle files from Groovy to Kotlin DSL
- updated to kotlin 2 and version catalog
- fixed some deprecations and warnings

#453 changed minSDK to 21

### CODE REVIEW

**Comment by Darkempire78** [comment]
Thanks for the PR, I'm in exams until Saturday, I'll look at it this weekend

**Comment by sosauce2** [comment]
Oh okay ! Bonne chance :)

**Comment by Darkempire78** [comment]
Can you solve the conflict please?

**Comment by sosauce2** [comment]
Done!

**Comment by Darkempire78** [comment]
thank you :)

**Pull request merged**
