### PR TITLE
Fixed issue #75 - Accessibility - Swipe down from anywhere to open history

### PR DESCRIPTION
**Pull request by subhajit-rajak**
Enabled accessibility to swipe down from anywhere to open history. I have used an Gesture Detector to detect swipe down gesture. Its also working way too smoothly.
Hope it helps.

Check recording below ->

https://github.com/user-attachments/assets/c38d107f-7969-4899-a425-5849bee06d06

### CODE REVIEW

**Comment by Darkempire78** [comment]
It does not work 🤔 In your video you show that we can swipe down from the only area that already works, not from everywhere
Screenshot_1

**Comment by subhajit-rajak** [comment]
I'm really sorry, give me a few minutes to fix that again.
Thank you for noting that out.

**Comment by subhajit-rajak** [comment]
@Darkempire78 I tried everything, but the app just isn't detecting any gestures. I took the reference from here 
[https://www.geeksforgeeks.org/how-to-detect-swipe-direction-in-android/](https://www.geeksforgeeks.org/how-to-detect-swipe-direction-in-android/)
Do you have any idea why it isn't working?

**Comment by Darkempire78** [comment]
> @Darkempire78 I tried everything, but the app just isn't detecting any gestures. I took the reference from here https://www.geeksforgeeks.org/how-to-detect-swipe-direction-in-android/ Do you have any idea why it isn't working?

yes, that's exactly what I said in the issue, I don't understand why it doesn't detect, it's really weird :/

**Comment by Darkempire78** [comment]
@subhajit-rajak Perhaps it's caused by https://github.com/hannesa2/AndroidSlidingUpPanel

**Comment by subhajit-rajak** [comment]
@Darkempire78 Ok, so I added a code snippet to disable touch for the sliding layout, and now it detects the gestures and the swipe down feature is working. But, on the digit buttons its not working

**Comment by Darkempire78** [comment]
> Its working on the vacant spaces besides the buttons
that's so weird 🤔

**Comment by subhajit-rajak** [comment]
Let me show you.
Check here

https://github.com/user-attachments/assets/e0274416-d1c4-4124-b95d-7d0bdd89cac5

**Comment by Darkempire78** [comment]
No idea how to fix that

**Pull request closed without merging**
